[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "838535098c341db7ea539861b2e000be7c1ec9f9"
lazy = true
llvm_version = "13"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "a2aeef8602888a15c39d0344ebf2964bccb7849a975aab1f9e1640da310641c3"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.x86_64-apple-darwin-llvm_version+13.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "a780dfcca47eef4543a2a5c26b67f2b72c5a14fc"
lazy = true
llvm_version = "13"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "62239ba5ca5cb82c21a991b8cb52297b6aa47f14186527c367a04e917759b11c"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.aarch64-apple-darwin-llvm_version+13.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "838535098c341db7ea539861b2e000be7c1ec9f9"
lazy = true
llvm_version = "13.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "a2aeef8602888a15c39d0344ebf2964bccb7849a975aab1f9e1640da310641c3"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.x86_64-apple-darwin-llvm_version+13.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "a780dfcca47eef4543a2a5c26b67f2b72c5a14fc"
lazy = true
llvm_version = "13.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "62239ba5ca5cb82c21a991b8cb52297b6aa47f14186527c367a04e917759b11c"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.aarch64-apple-darwin-llvm_version+13.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "fa07731144c965674b6aee5794970ea4c200f94c"
lazy = true
llvm_version = "14"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "c61cea13a4ad50cdbb36565014a0929b8616ae05731f9561b72797c56095ba49"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.x86_64-apple-darwin-llvm_version+14.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "6d1ca0d6e7c445e2da95cbc99f00b1e8164c4518"
lazy = true
llvm_version = "14"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "945f3d04e51dd2d697f7ac025bbf229f7f3230c789607acf52e499389ef7b3b3"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.aarch64-apple-darwin-llvm_version+14.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "fa07731144c965674b6aee5794970ea4c200f94c"
lazy = true
llvm_version = "14.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "c61cea13a4ad50cdbb36565014a0929b8616ae05731f9561b72797c56095ba49"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.x86_64-apple-darwin-llvm_version+14.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "6d1ca0d6e7c445e2da95cbc99f00b1e8164c4518"
lazy = true
llvm_version = "14.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "945f3d04e51dd2d697f7ac025bbf229f7f3230c789607acf52e499389ef7b3b3"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.4.0+0/Metal_LLVM_Tools.v0.4.0.aarch64-apple-darwin-llvm_version+14.asserts.tar.gz"
