[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "2287c8fc75003290ce875ccbccb9a595d2da1a7b"
lazy = true
llvm_version = "13"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "139c6823e386bf13131c7cae3ed8f3adb9d9891e1049da5a24c453aabc6d6eaf"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.x86_64-apple-darwin-llvm_version+13.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "999a2ffc07b7276fbd3dd3566d990c1b769e336d"
lazy = true
llvm_version = "13"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "a4e828b281db7572e5626c5d0d65c155afe4fdc90116fc8c2417e69491421263"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.aarch64-apple-darwin-llvm_version+13.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "2287c8fc75003290ce875ccbccb9a595d2da1a7b"
lazy = true
llvm_version = "13.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "139c6823e386bf13131c7cae3ed8f3adb9d9891e1049da5a24c453aabc6d6eaf"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.x86_64-apple-darwin-llvm_version+13.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "999a2ffc07b7276fbd3dd3566d990c1b769e336d"
lazy = true
llvm_version = "13.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "a4e828b281db7572e5626c5d0d65c155afe4fdc90116fc8c2417e69491421263"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.aarch64-apple-darwin-llvm_version+13.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "f3694bd22e761becfb90fc9dce0f395f0bb7d51d"
lazy = true
llvm_version = "14"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "ec1ba645ca69e2c2cac6fd368701401c553e10ce036113e6dbacb58bccd1a371"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.x86_64-apple-darwin-llvm_version+14.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "b36b48010d7b130f4e4b74c9c18e114a5e70f180"
lazy = true
llvm_version = "14"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "33fa30e24f1a1c9a1b7b9fa8ab245399dd525e78068bce36725901cdc44741e3"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.aarch64-apple-darwin-llvm_version+14.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "f3694bd22e761becfb90fc9dce0f395f0bb7d51d"
lazy = true
llvm_version = "14.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "ec1ba645ca69e2c2cac6fd368701401c553e10ce036113e6dbacb58bccd1a371"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.x86_64-apple-darwin-llvm_version+14.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "b36b48010d7b130f4e4b74c9c18e114a5e70f180"
lazy = true
llvm_version = "14.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "33fa30e24f1a1c9a1b7b9fa8ab245399dd525e78068bce36725901cdc44741e3"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.aarch64-apple-darwin-llvm_version+14.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "0cc1b8676be7d12dda69ab7bbdc3c334681c63cc"
lazy = true
llvm_version = "15"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "c8c80fc8b8111af212da7b3fc8d6f3e61da3ef382c7efd878ca3d6e99592e736"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.x86_64-apple-darwin-llvm_version+15.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "684ba5115eba30f1f101223ccfb636cbb4d68fae"
lazy = true
llvm_version = "15"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "b104fd125901aca459e912c7a5e81d9960672b34dba782d43796c9439939c1e6"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.aarch64-apple-darwin-llvm_version+15.tar.gz"
[[Metal_LLVM_Tools]]
arch = "x86_64"
git-tree-sha1 = "0cc1b8676be7d12dda69ab7bbdc3c334681c63cc"
lazy = true
llvm_version = "15.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "c8c80fc8b8111af212da7b3fc8d6f3e61da3ef382c7efd878ca3d6e99592e736"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.x86_64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[Metal_LLVM_Tools]]
arch = "aarch64"
git-tree-sha1 = "684ba5115eba30f1f101223ccfb636cbb4d68fae"
lazy = true
llvm_version = "15.asserts"
os = "macos"

    [[Metal_LLVM_Tools.download]]
    sha256 = "b104fd125901aca459e912c7a5e81d9960672b34dba782d43796c9439939c1e6"
    url = "https://github.com/JuliaBinaryWrappers/Metal_LLVM_Tools_jll.jl/releases/download/Metal_LLVM_Tools-v0.5.1+0/Metal_LLVM_Tools.v0.5.1.aarch64-apple-darwin-llvm_version+15.asserts.tar.gz"
